### ISSUE TITLE
请求URL超时

### ISSUE THREAD

**Issue by papi888** [Soopro/wechat_subscribers#12]
在微信平台绑定TOKEN和URL的时候，一直弹出"请求URL超时"，求解！

**Comment by robin-zhao** [comment]
这个是你站点的问题吧。

**Comment by redyyu** [comment]
如果遇到在绑定微信接口的时候出现 URL请求超时 这类错误的时候，多半是因为你的网站和微信服务器之间的比较慢，又加上这个插件是实用WP原生的API，这样绕过一圈以后就来不及响应了。可以尝试用 作弊 的方式，想见插件目录内的Readme。

更多帮助看之类，我把人们经常遇到的 问题陆续收集起来。
http://imredy.com/wp-wechat/
