### ISSUE TITLE
如何恢复之前的自定义菜单

### ISSUE THREAD

**Issue by gztitan** [Soopro/wechat_subscribers#13]
由于插件通过接口修改了菜单配置，原来的菜单失效，如何恢复？谢谢

**Comment by redyyu** [comment]
插件 没有接口修改菜单配置，是微信公众平台在你接入第三方以后禁止了。
如果你要开启菜单，那么你必须要通过微信的认证，就是300块钱哪个。然后必须要有使用一个支持菜单管理的第三方接入。（这个插件只服务于免费的微信公众号玩家，于是，它是不支持菜单的。）

恢复菜单这个，我不确定停止绑定第三方接入会不会恢复。如果不能恢复的话。也许只能通过时光穿越之类的科技，重返过去备份这个菜单。考虑到现在这方面的影视剧多的好像野狗一样，于是我大胆预测，再等120年左右人类将具备这一项技术，那时应该可以恢复了。。。。。感谢微信，给人类文明的发展以动力！
