### ISSUE TITLE
需求：自定义菜单

### ISSUE THREAD

**Issue by Haber-He** [Soopro/wechat_subscribers#3]
版主好人啊，提个需求：增加自定义菜单

**Comment by supmice** [comment]
自定义菜单 需要 有微信认证才行。不适合免费的微认证账号使用，近期没有计划增加。
如果你期望是哪两个未经认证也可以用的新接口，那么你需要知道，要使那两个接口完成工作，
必须要另一个经过认证的微信号去先将内容提交到微信服务器，于是这变成了一个蛋和鸡的问题，结果还是必要有一个认证过的号。
实际上文档中有提到那两个接口是给第三方多用户平台设计的。




茹歆燁 Redy Ru
MANAGING DIRECTOR & PRODUCT DESIGNER
Email: redy@soopro.com <mailto:redy@soopro.com>
Mobile: +86 1395 8108 444
宿樸信息科技
No.601 Jin Jian Rd.20
Yangpu District
Shanghai 200433
+86 21 55573387
