### ISSUE TITLE
列表在WP更新后，无法显示

### ISSUE THREAD

**Issue by congcong009** [Soopro/wechat_subscribers#5]
![bug-](https://cloud.githubusercontent.com/assets/2680017/13207834/147a96da-d94e-11e5-8907-b53bca383761.png)

wp在更新至最新版本后，什么都没做（也许是WP数据库的升级操作，暂时不清楚重现步骤），自定义回复列表显示为空，但是旁边显示有项目，数据库中查询结果如下。
![default](https://cloud.githubusercontent.com/assets/2680017/13208286/39f4b4a0-d952-11e5-9afd-1af29ec58d06.png)

删除重新安装后问题依然存在，因为删除操作只删除了文件，没有清理掉数据，不清楚是否有影响配置更新。

输入新项目，公众号可以正常响应，说明配置成功，只是列表依然无法使用。

清空并重新输入Token，列表信息依然无法刷新。

插件已经安装至最新版本1.60.

目前并不影响使用，但需要配合数据库操作，烦请查看一下，谢谢。

**Comment by redyyu** [comment]
后来好像是搞定了吗？ 没有的话 联系我吧。

**Comment by congcong009** [comment]
后来我是直接在数据库录入的配置，然后运行起来是没问题的，不影响使用。

只是我不知道如何复现（唯一可能存在的原因是数据迁移，我全站从腾讯云迁移到了阿里云），所以也没办法告诉具体步骤，无法帮忙优化，如果其他用户遇到类似问题不清楚他们能否在数据库里填配置解决 :(

**Comment by redyyu** [comment]
方便的话，把你出问题的 那个数据表 倒出来 让我看看？
